# Generated by Django 6.1.1 on 2026-09-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reviewer',
            new_name='reviewer_id',
        ),
    ]
