# Generated by Django 6.1.1 on 2026-09-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0006_rename_reviewer_task_reviewer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
